### ISSUE TITLE
Chrome doesn't allow to download Windows release

### ISSUE THREAD

**Issue by Marfa** [Eliya-G/coffee-o-clock#4]
![CleanShot 2024-09-26 at 10 10 18@2x](https://github.com/user-attachments/assets/2eff27c5-6ba5-4a22-bafb-11f859093e2a)

I'm on Chrome 129.0.6668.70 Win 11. It blocks download of this link https://github.com/Eliya-G/coffee-o-clock/releases/download/v1.0.2/Coffee-o-clock_Windows_Portable.zip . Reason https://support.google.com/chrome/answer/6261569

**Comment by Eliya-G** [comment]
They miss flagged the Windows zip. I'm working on sorting this out.

The Git repository can still be cloned and used. 

Thanks for letting me know.

**Comment by Eliya-G** [comment]
Google's-operated "Safe-Browsing" reputation service false flagged the program. To my knowledge there's no way to appeal it. 

I'll take down the Windows release till I find a way to rectify the issue.
